### ISSUE TITLE
Configuration doesn't recognize initialization as class property

### ISSUE THREAD

**Issue by chpmrc** [Hipo/eslint-config-hipo-base#1]
Please see screenshot: https://cl.ly/1790e1178e31/Image%202019-01-23%20at%201.26.29%20PM.png

**Comment by mucahit** [comment]
Hey @chpmrc 

Let's make sure your `.eslintrc` config file contains `parser` config. Also, you need to install `eslint-plugin-babel` package.

```javascript
{
  // other configs,
  "parser": "babel-eslint"
}
```

**Comment by chpmrc** [comment]
I did and now I'm getting all sorts of errors.
- React unused: https://cl.ly/0a97c662c056
- Import used but reported as unused: https://cl.ly/608ec8d513a5
- Shadowing outer scope raises an error (even though using the same name as the imported action is a known pattern with Redux): https://cl.ly/2df3a7777618

**Comment by edizcelik** [comment]
This was a configuration issue. So I'm closing it.
