### ISSUE TITLE
Enable `import/order` Rule

### ISSUE THREAD

**Issue by mucahit** [Hipo/eslint-config-hipo-base#8]
We [discussed](https://github.com/Hipo/hipo-frontend-project-starter/pull/1#discussion_r317948518) with @edizcelik about this rule and I think `import/order` isn't active in common ESLint configs. If so, let's enable.

```javascript
"import/order": [
  "error",
  {
    "groups": [
      [
        "external",
        "internal"
      ],
      [
        "sibling",
        "parent"
      ]
    ],
    "newlines-between": "always"
  }
],
```

**Comment by brkn** [comment]
What's the update about this, why did we removed it back at this commit?
https://github.com/Hipo/eslint-config-hipo-base/commit/d1001d5acffe8b7d400b118a0ef58f4cf0d31ceb

**Comment by edizcelik** [comment]
I don't remember why we rolled back on these rules after adding them. @mucahit any idea ? I think we can close this.

**Comment by mucahit** [comment]
> I don't remember why we rolled back on these rules after adding them. @mucahit any idea ? I think we can close this.

I'm not sure, it seems it's not an issue anymore. Closing this.
